<a href="https://colab.research.google.com/github/shhh-33/sesac-python/blob/shhh/0317.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!sudo apt-get install -y fonts-nanum
#!sudo fc-cache -fv
#!rm ~/.cache/matplotlib -rf
# 1. 최초 실행 후 런타임 재기동 하시고,
# 2. 런타임 재기동 후 주석 처리하세요.

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl

mpl.rcParams['axes.unicode_minus'] = False
mpl.rcParams['font.family'] = "NanumBarunGothic"

#%matplotlib inline


Mounted at /content/drive


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl

#%matplotlib inline


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


데이터 준비하기

In [ ]:
bream_length = [25.4, 26.3, 26.5, 29.0, 29.0, 29.7, 29.7, 30.0, 30.0, 30.7, 31.0, 31.0, 
                31.5, 32.0, 32.0, 32.0, 33.0, 33.0, 33.5, 33.5, 34.0, 34.0, 34.5, 35.0, 
                35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 38.5, 38.5, 39.5, 41.0, 41.0]
bream_weight = [242.0, 290.0, 340.0, 363.0, 430.0, 450.0, 500.0, 390.0, 450.0, 500.0, 475.0, 500.0, 
                500.0, 340.0, 600.0, 600.0, 700.0, 700.0, 610.0, 650.0, 575.0, 685.0, 620.0, 680.0, 
                700.0, 725.0, 720.0, 714.0, 850.0, 1000.0, 920.0, 955.0, 925.0, 975.0, 950.0]

In [ ]:
smelt_length = [9.8, 10.5, 10.6, 11.0, 11.2, 11.3, 11.8, 11.8, 12.0, 12.2, 12.4, 13.0, 14.3, 15.0]
smelt_weight = [6.7, 7.5, 7.0, 9.7, 9.8, 8.7, 10.0, 9.9, 9.8, 12.2, 13.4, 12.2, 19.7, 19.9]

In [ ]:
length = bream_length + smelt_length
weight = bream_weight + smelt_weight

In [ ]:
fish_data = [(l,w) for l , w in zip(length, weight)]

In [ ]:
fish_target = [1] * 35 + [0] *14

In [ ]:
len(fish_data) 

49

In [ ]:
len(fish_target)

49

훈련하기

In [ ]:
#p53
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
kn = KNeighborsClassifier() #k = 5 (defalut)

In [ ]:
kn.fit(fish_data,fish_target)

KNeighborsClassifier()

In [ ]:
kn.effective_metric_

'euclidean'

In [ ]:
kn._fit_X.shape #49행 

(49, 2)

In [ ]:
kn._fit_X #

array([[  25.4,  242. ],
       [  26.3,  290. ],
       [  26.5,  340. ],
       [  29. ,  363. ],
       [  29. ,  430. ],
       [  29.7,  450. ],
       [  29.7,  500. ],
       [  30. ,  390. ],
       [  30. ,  450. ],
       [  30.7,  500. ],
       [  31. ,  475. ],
       [  31. ,  500. ],
       [  31.5,  500. ],
       [  32. ,  340. ],
       [  32. ,  600. ],
       [  32. ,  600. ],
       [  33. ,  700. ],
       [  33. ,  700. ],
       [  33.5,  610. ],
       [  33.5,  650. ],
       [  34. ,  575. ],
       [  34. ,  685. ],
       [  34.5,  620. ],
       [  35. ,  680. ],
       [  35. ,  700. ],
       [  35. ,  725. ],
       [  35. ,  720. ],
       [  36. ,  714. ],
       [  36. ,  850. ],
       [  37. , 1000. ],
       [  38.5,  920. ],
       [  38.5,  955. ],
       [  39.5,  925. ],
       [  41. ,  975. ],
       [  41. ,  950. ],
       [   9.8,    6.7],
       [  10.5,    7.5],
       [  10.6,    7. ],
       [  11. ,    9.7],
       [  11.2,    9.8],


In [ ]:
x, y =2,3
x +y

5

In [ ]:
_ #파이썬에서 _ : 1.마지막 명령문의 결과를 담는 변수

5

In [ ]:
result =0
for _ in range(1,6):
  print('A')

A
A
A
A
A


In [ ]:
class MyClass(object):
  def __init__(self):
    pass
  def test_method(self):
    pass
  
my_obj = MyClass()
my_obj.test_method()

In [ ]:
1_000_000

1000000

In [ ]:
attrs =dir(kn)
attrs

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_algorithm_metric',
 '_check_feature_names',
 '_check_n_features',
 '_estimator_type',
 '_fit',
 '_fit_X',
 '_fit_method',
 '_get_param_names',
 '_get_tags',
 '_kneighbors_reduce_func',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_tree',
 '_validate_data',
 '_y',
 'algorithm',
 'classes_',
 'effective_metric_',
 'effective_metric_params_',
 'fit',
 'get_params',
 'kneighbors',
 'kneighbors_graph',
 'leaf_size',
 'metric',
 'metric_params',
 'n_features_in_',
 'n_jobs',
 'n_neighbors',
 'n_samples_fi

In [ ]:
import re
#정규표현식
p =re.compile('_[a-z]+') 
for attr in attrs:
  if p.match(attr):
    print(attr)

_abc_impl
_check_algorithm_metric
_check_feature_names
_check_n_features
_estimator_type
_fit
_fit_X
_fit_method
_get_param_names
_get_tags
_kneighbors_reduce_func
_more_tags
_pairwise
_repr_html_
_repr_html_inner
_repr_mimebundle_
_tree
_validate_data
_y


In [ ]:
kn3 = KNeighborsClassifier(n_neighbors=3)
kn3.fit(fish_data, fish_target)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
kn49 = KNeighborsClassifier(n_neighbors=49)
kn49.fit(fish_data, fish_target)

KNeighborsClassifier(n_neighbors=49)

In [ ]:
kn3.score(fish_data, fish_target)

1.0

In [ ]:
kn49.score(fish_data, fish_target)  #크기가 커지니까

0.7142857142857143

In [ ]:
35/49

0.7142857142857143

평가하기

In [ ]:
kn.predict([[30,500]])

array([1])

In [ ]:
kn.predict([[30,500],[25,100]])

array([1, 0])

In [ ]:
kn.score(fish_data ,fish_target)

1.0

In [ ]:
from sklearn.metrics import accuracy_score