<a href="https://colab.research.google.com/github/shhh-33/Python/blob/shhh/Machine%20Learning/d06_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%run my_init.py

Mounted at /content/drive


In [ ]:
%matplotlib inline

In [ ]:
df = pd.read_csv('https://bit.ly/perch_csv_data')
df.head()

length   height   width
0     8.4     2.11    1.41
1    13.7     3.53    2.00
2    15.0     3.82    2.43
3    16.2     4.59    2.63
4    17.4     4.59    2.94

In [ ]:
perch_full = df.to_numpy()
perch_full[:5]

array([[ 8.4 ,  2.11,  1.41],
       [13.7 ,  3.53,  2.  ],
       [15.  ,  3.82,  2.43],
       [16.2 ,  4.59,  2.63],
       [17.4 ,  4.59,  2.94]])

In [ ]:
perch_weight = np.array([5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 110.0,
       115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 130.0,
       150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 197.0,
       218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 514.0,
       556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 820.0,
       850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 1000.0,
       1000.0])

In [ ]:
perch_full.shape, perch_weight.shape

((56, 3), (56,))

In [ ]:
train_input, test_input, train_target, test_target = train_test_split(perch_full, perch_weight, random_state=42)

In [ ]:
train_input.shape, train_target.shape

((42, 3), (42,))

In [ ]:
test_input.shape, test_target.shape

((14, 3), (14,))

In [ ]:
poly = PolynomialFeatures(degree=2, include_bias=False)
train_poly = poly.fit_transform(train_input)
train_poly.shape

(42, 9)

In [ ]:
poly.get_feature_names_out()

array(['x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2',
       'x2^2'], dtype=object)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   length   56 non-null     float64
 1    height  56 non-null     float64
 2    width   56 non-null     float64
dtypes: float64(3)
memory usage: 1.4 KB


In [ ]:
test_poly = poly.transform(test_input)

In [ ]:
test_poly.shape

(14, 9)

In [ ]:
lr = LinearRegression()
lr.fit(train_poly, train_target)

LinearRegression()

In [ ]:
r2_score(train_target, lr.predict(train_poly))

0.9903183436982124

In [ ]:
r2_score(test_target, lr.predict(test_poly))

0.9714559911594134

In [ ]:
for n in range(1, 6):
  poly = PolynomialFeatures(degree=n, include_bias=False)
  train_poly = poly.fit_transform(train_input)
  test_poly = poly.transform(test_input)
  lr = LinearRegression()
  lr.fit(train_poly, train_target)
  print(f"degree:{n}, feature #: {train_poly.shape[1]}")
  print(f"train score: {r2_score(train_target, lr.predict(train_poly))}")
  print(f"test score: {r2_score(test_target, lr.predict(test_poly))}", end='\n\n')

degree:1, feature #: 3
train score: 0.9559326821885706
test score: 0.8796419177546367

degree:2, feature #: 9
train score: 0.9903183436982124
test score: 0.9714559911594134

degree:3, feature #: 19
train score: 0.99638723409801
test score: 0.9410534492233222

degree:4, feature #: 34
train score: 0.9995286898074609
test score: -6.7866969165723585

degree:5, feature #: 55
train score: 0.9999999999991097
test score: -144.40579242684848



In [ ]:
poly = PolynomialFeatures(degree=3, include_bias=True)
train_poly = poly.fit_transform(train_input)
poly.get_feature_names_out()

array(['1', 'x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2',
       'x2^2', 'x0^3', 'x0^2 x1', 'x0^2 x2', 'x0 x1^2', 'x0 x1 x2',
       'x0 x2^2', 'x1^3', 'x1^2 x2', 'x1 x2^2', 'x2^3'], dtype=object)

In [ ]:
train_poly.shape, test_poly.shape

((42, 20), (14, 55))

In [ ]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_poly)
train_scaled = ss.transform(train_poly)
test_scaled = ss.transform(test_poly)

ValueError: ignored

In [ ]:
ss.mean_

array([1.00000000e+00, 2.84452381e+01, 8.04238095e+00, 4.82047619e+00,
       8.85315000e+02, 2.53486881e+02, 1.51959000e+02, 7.29365000e+01,
       4.36999452e+01, 2.62868381e+01, 2.97326070e+04, 8.59817581e+03,
       5.15200651e+03, 2.49680043e+03, 1.49567194e+03, 8.99184494e+02,
       7.27945149e+02, 4.36019840e+02, 2.62115117e+02, 1.58141990e+02])

In [ ]:
ss.scale_

array([1.00000000e+00, 8.72831196e+00, 2.87343151e+00, 1.74638123e+00,
       5.24782988e+02, 1.60836428e+02, 9.64793789e+01, 4.95165749e+01,
       2.97578956e+01, 1.81139412e+01, 2.50155373e+04, 7.49275582e+03,
       4.47153009e+03, 2.25433695e+03, 1.34683566e+03, 8.11988865e+02,
       6.81265335e+02, 4.07639942e+02, 2.46263218e+02, 1.50164227e+02])

In [ ]:
lr = LinearRegression()
lr.fit(train_scaled, train_target)

LinearRegression()

In [ ]:
r2_score(train_target, lr.predict(train_scaled))

0.9963872340980068

In [ ]:
r2_score(test_target, lr.predict(test_scaled))

NameError: ignored

In [ ]:
from sklearn.linear_model import Ridge

ridge = Ridge()
ridge.fit(train_scaled, train_target)

In [ ]:
r2_score(train_target, ridge.predict(train_scaled))

In [ ]:
r2_score(test_target, ridge.predict(test_scaled))

In [ ]:
lr.coef_

In [ ]:
ridge.coef_

In [ ]:
for n in [0.001, 0.01, 0.1, 1, 10, 100, 1000]:
  ridge = Ridge(alpha=n)
  ridge.fit(train_scaled, train_target)
  print(f"alpha:{n}")
  print(f"train score: {r2_score(train_target, ridge.predict(train_scaled))}")
  print(f"test score: {r2_score(test_target, ridge.predict(test_scaled))}", end='\n\n')

In [ ]:
train_score, test_score = [], []
alphas = [0.001, 0.01, 0.1, 1, 10, 100, 1000]
for n in alphas:
  ridge = Ridge(alpha=n)
  ridge.fit(train_scaled, train_target)
  train_score.append(r2_score(train_target, ridge.predict(train_scaled)))
  test_score.append(r2_score(test_target, ridge.predict(test_scaled)))

In [ ]:
plt.plot(np.log10(alphas), train_score)
plt.plot(np.log10(alphas), test_score)
plt.xlabel('log10(alpha)')
plt.ylabel('score')
plt.show()

In [ ]:
from sklearn.linear_model import Lasso

lasso = Lasso()
lasso.fit(train_scaled, train_target)

In [ ]:
r2_score(train_target, lasso.predict(train_scaled))

In [ ]:
r2_score(test_target, lasso.predict(test_scaled))

In [ ]:
import warnings

warnings.filterwarnings(action='ignore')

In [ ]:
alphas = [0.001, 0.01, 0.1, 10, 100]
for n in alphas:
  lasso = Lasso(alpha=n)
  lasso.fit(train_scaled, train_target)
  print(f"alpha:{n}")
  print(f"train score: {r2_score(train_target, lasso.predict(train_scaled))}")
  print(f"test score: {r2_score(test_target, lasso.predict(test_scaled))}", end='\n\n')

In [ ]:
lasso.alpha

In [ ]:
lasso.coef_

In [ ]:
train_score, test_score = [], []
alphas = [0.001, 0.01, 0.1, 1, 10, 100]
for n in alphas:
  lasso = Lasso(alpha=n)
  lasso.fit(train_scaled, train_target)
  train_score.append(r2_score(train_target, lasso.predict(train_scaled)))
  test_score.append(r2_score(test_target, lasso.predict(test_scaled)))

In [ ]:
plt.plot(np.log10(alphas), train_score)
plt.plot(np.log10(alphas), test_score)
plt.xlabel('log10(alpha)')
plt.ylabel('score')
plt.show()

In [ ]:
np.sum(lasso.coef_ == 0)

In [ ]:
poly.get_feature_names_out()

In [ ]:
lasso.coef_ != 0

In [ ]:
poly.get_feature_names_out()[lasso.coef_ != 0]