<a href="https://colab.research.google.com/github/shhh-33/Python/blob/shhh/Machine%20Learning/d09_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%run my_init.py

Mounted at /content/drive


In [ ]:
%matplotlib inline

In [ ]:
wine = pd.read_csv("https://bit.ly/wine_csv_data")
wine.head(3)

alcohol  sugar    pH  class
0      9.4    1.9  3.51    0.0
1      9.8    2.6  3.20    0.0
2      9.8    2.3  3.26    0.0

In [ ]:
data = wine.drop('class', axis=1).to_numpy()
data.shape

(6497, 3)

In [ ]:
target = wine['class'].to_numpy()
target.shape

(6497,)

In [ ]:
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)

In [ ]:
train_input.shape, train_target.shape

((5197, 3), (5197,))

In [ ]:
test_input.shape, test_target.shape

((1300, 3), (1300,))

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

In [ ]:
from sklearn.model_selection import cross_validate

scores = cross_validate(dt, train_input, train_target, cv=3, return_train_score=True)
scores

{'fit_time': array([0.00679994, 0.00617242, 0.00740194]),
 'score_time': array([0.00090122, 0.00080776, 0.00086737]),
 'test_score': array([0.84535488, 0.87182448, 0.84757506]),
 'train_score': array([0.99711316, 0.9979798 , 0.9979798 ])}

In [ ]:
np.mean(scores['test_score']) # validation score

0.8549181380146386

In [ ]:
np.mean(scores['train_score'])

0.9976909199772942

In [ ]:
from sklearn.model_selection import KFold, StratifiedKFold

kfold = KFold(3, shuffle=True, random_state=42)
skfold = StratifiedKFold(3, shuffle=True, random_state=42)

In [ ]:
scores = cross_validate(dt, train_input, train_target, cv=skfold, return_train_score=True)
scores

{'fit_time': array([0.0093987 , 0.00635648, 0.00615048]),
 'score_time': array([0.00090551, 0.00093722, 0.00079751]),
 'test_score': array([0.85920369, 0.85450346, 0.84237875]),
 'train_score': array([0.99682448, 0.998557  , 0.9979798 ])}

In [ ]:
np.arange(0.0001, 0.0006, 0.0001)

array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005])

In [ ]:
for i, v in enumerate(np.arange(0.0003, 0.0008, 0.0001)):
  dt = DecisionTreeClassifier(min_impurity_decrease=v, random_state=42)
  scores = cross_validate(dt, train_input, train_target, cv=skfold, return_train_score=True)
  print(f"[{i+1}]")
  print(f"train score: {np.mean(scores['train_score'])}")
  print(f"test score: {np.mean(scores['test_score'])}", end="\n\n")

[1]
train score: 0.9295742257058653
test score: 0.8637674370670857

[2]
train score: 0.9119681362175589
test score: 0.863958782267153

[3]
train score: 0.9000382412045229
test score: 0.8654987613091344

[4]
train score: 0.8947468748854431
test score: 0.8668459514554007

[5]
train score: 0.8869535562376208
test score: 0.8631911803966564



In [ ]:
from sklearn.model_selection import GridSearchCV

dt = DecisionTreeClassifier(random_state=42)
params = {
    "max_depth": range(3, 6),
    "min_samples_split": [2, 5, 8],
    "min_impurity_decrease": np.arange(0.0001, 0.0006, 0.0001)
}

In [ ]:
3 * 3 * 5 * 5

225

In [ ]:
gs = GridSearchCV(dt, params, cv=5, n_jobs=-1)
gs.fit(train_input, train_target)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': range(3, 6),
                         'min_impurity_decrease': array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005]),
                         'min_samples_split': [2, 5, 8]})

In [ ]:
gs.best_estimator_

DecisionTreeClassifier(max_depth=5,
                       min_impurity_decrease=0.00030000000000000003,
                       random_state=42)

In [ ]:
gs.best_params_

{'max_depth': 5,
 'min_impurity_decrease': 0.00030000000000000003,
 'min_samples_split': 2}

In [ ]:
gs.best_score_

0.8585735174354039

In [ ]:
gs.cv_results_.keys()

dict_keys(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'param_max_depth', 'param_min_impurity_decrease', 'param_min_samples_split', 'params', 'split0_test_score', 'split1_test_score', 'split2_test_score', 'split3_test_score', 'split4_test_score', 'mean_test_score', 'std_test_score', 'rank_test_score'])

In [ ]:
gs.cv_results_['mean_test_score']

array([0.84125583, 0.84125583, 0.84125583, 0.84125583, 0.84125583,
       0.84125583, 0.84125583, 0.84125583, 0.84125583, 0.84125583,
       0.84125583, 0.84125583, 0.84125583, 0.84125583, 0.84125583,
       0.85337806, 0.85337806, 0.85337806, 0.85337806, 0.85337806,
       0.85337806, 0.85337806, 0.85337806, 0.85337806, 0.85337806,
       0.85337806, 0.85337806, 0.85318557, 0.85318557, 0.85318557,
       0.85780355, 0.85780355, 0.85799604, 0.85799604, 0.85799604,
       0.85799604, 0.85857352, 0.85857352, 0.85857352, 0.85857352,
       0.85857352, 0.85857352, 0.85838102, 0.85838102, 0.85838102])

In [ ]:
np.max(gs.cv_results_['mean_test_score'])

0.8585735174354039

In [ ]:
best_model = gs.best_estimator_
best_model.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': 5,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.00030000000000000003,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': 42,
 'splitter': 'best'}

In [ ]:
best_model.score(train_input, train_target)

0.8668462574562248

In [ ]:
best_model.score(test_input, test_target)

0.8623076923076923

#### probability distribution

In [ ]:
from scipy.stats import uniform, randint, norm, poisson, gamma, beta, bernoulli

In [ ]:
ud = uniform(0, 1)
ud.rvs(10, random_state=42)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [ ]:
ud.rvs((4, 5), random_state=42)

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914]])

In [ ]:
nd = norm(60, 5)
nd.rvs((4, 5), random_state=42)

array([[62.48357077, 59.30867849, 63.23844269, 67.61514928, 58.82923313],
       [58.82931522, 67.89606408, 63.83717365, 57.65262807, 62.71280022],
       [57.68291154, 57.67135123, 61.20981136, 50.43359878, 51.37541084],
       [57.18856235, 54.9358444 , 61.57123666, 55.45987962, 52.93848149]])

In [ ]:
params = {
    "max_depth": randint(3, 50),
    "min_samples_split": randint(2, 20),
    "min_impurity_decrease": uniform(0.00001, 0.001)
}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

rs = RandomizedSearchCV(dt, params, n_iter=500, n_jobs=-1, cv=10, random_state=42)
rs.fit(train_input, train_target)

RandomizedSearchCV(cv=10, estimator=DecisionTreeClassifier(random_state=42),
                   n_iter=500, n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f033586d150>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f033586d850>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f033586d550>},
                   random_state=42)

In [ ]:
rs.best_score_

0.8731951237587076

In [ ]:
rs.best_params_

{'max_depth': 42,
 'min_impurity_decrease': 0.00023902539092479635,
 'min_samples_split': 8}

In [ ]:
dt = rs.best_estimator_
accuracy_score(train_target, dt.predict(train_input))

0.9141812584183182

In [ ]:
accuracy_score(test_target, dt.predict(test_input))

0.8669230769230769